### ISSUE TITLE
Missing answers to challenges

### ISSUE THREAD

**Issue by DrMaggie** [datacarpentry/R-ecology-lesson#718] opened 2021-05-09 13:28 UTC
Hi, 

My apologies in advance if creating a new issue "on top of" an existing but now closed one is against github "netiquette", but I'm quite new to this platform! 

Very similar to the now closed issue #717 (https://github.com/datacarpentry/R-ecology-lesson/issues/717), I am experiencing pretty much the same problem: when visiting the part of the web page https://datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html that describes the ggplot challenge to customize  violin & box plots, there is no  clickable "button" to expand & show the solution code. I attach a screen shot of the relevant part of the page as displayed in my browser:
![screenshot](https://user-images.githubusercontent.com/8366663/117573962-292be100-b0db-11eb-8d3d-44ad6ceccb89.jpg)

Maybe the fix that was applied before the 717 issue was closed somehow doesn't work for all browsers? (I use the latest version of Chrome for Windows 10 (Version 90.0.4430.93, official 64-bit build)...)

Best regards,
Maggie

**Comment by Teebusch** [comment] 2021-05-10 08:53
Hi @DrMaggie , thank you for bringing this up. To me it looks like for this particular challenge there is no answer provided in the code, so the problem is not that the expand button is broken (#717), but that there is nothing to expand (new issue).

To solve this we would have to add an answer block -- somthing like this:

```r
> ```{r boxplot-challenge, answer=TRUE, purl=FALSE}
> # violinplot
> ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
>     geom_violin() +
>    geom_jitter(alpha = 0.3, color = "tomato") +
>    scale_y_log10()
> 
> # hindfoot length boxplot
> ggplot(mapping = aes(x = species_id, y = hindfoot_length)) +
>    geom_boxplot(alpha = 0) +
>   geom_jitter(mapping = aes(color = as_factor(plot_id)))
>```
```

I don't have time to test this and make a PR right now. In particular, I'm not sure the `as_factor()` is even necassary, since we moved to tidyverse's `read_csv()`. If it isn't, then that part should be removed from the challenge.

**Comment by DrMaggie** [comment] 2021-05-10 11:44
Dear @Teebusch ,

thank you so much for addressing my question, and for providing the solution code - it is very much appreciated, and really helped me to better understand the possibilities of ggplot!

A more general observation from my side is that it would be very helpful if all challenges were formatted in the same way, i.e. always be provided with a "view answer button" - even if there is no associated code or text (except  "no answer available"). This would IMHO enhance the experience of learners (and instructors alike)! 

In any case, I'm happy to close this issue now.

Best regards,
Maggie

**Comment by DrMaggie** [comment] 2021-05-11 14:28
@Teebusch, thanks for following up on the issue, and giving it a much more descriptive title!

**Comment by tobyhodges** [comment] 2024-07-10 10:41
Thanks both for contributing to this discussion. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As this issue relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you believe that some or all of the changes being discussed here remain relevant to the redesigned lesson, linking to this thread where appropriate.

**Closed by tobyhodges** 2024-07-10 10:41 UTC
Labels: type:clarification
