### ISSUE TITLE
Announcement: The default branch for this repository is now `main`

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#617] opened 2020-06-18 09:55 UTC
Dear @datacarpentry/r-ecology-lesson-maintainers 

This issue is to inform you that the default branch for this repository is now `main`.
I haven't deleted `master` yet but please make sure that for your next push to the repository you use

```bash
git push -u upstream main
```

(assuming you've named the remote for this repository `upstream`).

Let me know if you have any questions or concerns. Thanks!

**Comment by Teebusch** [comment] 2021-07-05 18:35
I suggest to close this issue and maybe add the information to the `CONTRIBUTING.Rmd`. Alternatively, the issue could be pinned, but I don't think it's that important. 

A year after it has been posted, the issue is buried between lots of other issues. I doubt that it is still useful.

**Closed** 2024-07-10 10:35 UTC
