### ISSUE TITLE
RFC: Migration to R 4.0

### ISSUE THREAD

**Issue by zkamvar** [datacarpentry/R-ecology-lesson#629] opened 2020-07-27 17:04 UTC
During the June Maintainer meeting, we asked for comments and experiences with the migration to R 4.0 so that we could create guidance for maintainers and instructors. We have drafted a short blog post (https://github.com/carpentries/carpentries.org/pull/830) to be released next week (2020-08-03) that describes our recommendations for migration. You can find a [preview of the blog post here](https://deploy-preview-830--stupefied-einstein-5bde90.netlify.app/blog/2020/08/r-4-migration/). **Please look over the blog posts and make comments by 2020-07-30 so that we can incoroporate any changes before the post goes live.**

To help identify the differences between R 3.6 and R 4.0, I have run this lesson in both versions and [posted the results](https://github.com/zkamvar/postmaul/blob/master/analysis.md#lesson-R-ecology-lesson) that show the differences in output chunks and entire markdown files.

**Comment by Teebusch** [comment] 2020-10-03 14:34
Issue can be closed since the deadline for commenting on the blog post has passed.
I went through the diffs provided by @zkamvar  - they show that character columns in the data are not automatically converted to factors anymore. This is already tracked by a couple of other issues here, so no need to keep this one open, I think.

**Comment by zkamvar** [comment] 2020-10-05 15:51
Ultimately, it's up to the maintainers of this repo. My instinct would be to close this issue once the lesson itself is compliant with R 4.0.

**Comment by Teebusch** [comment] 2020-10-05 16:05
> Ultimately, it's up to the maintainers of this repo. My instinct would be to close this issue once the lesson itself is compliant with R 4.0.

The issue is about a "request for comment (RFC)" on a blog post that was released in July, not about compatibility with R >4.0. Regarding the latter, there are a handful of more or less general issues to keep track of it.
But of course it is up to the maintainers. I'm just trying to point out an issue that seems to serve no purpose.

**Comment by fmichonneau** [comment] 2020-10-07 09:32
I agree the other issues are tracked elsewhere

**Closed by fmichonneau** 2020-10-07 09:32 UTC
